"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$time\
$username\
$directory\
$os\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
\n$character\
"""

# Ensure username is always shown
[username]
show_always = true
style_user = "bold blue"
format = "[ $user ]($style) "
   
# Enable and configure the time module
[time]
disabled = false
time_format = "%R" # Hour:Minute format (e.g., 14:30)
style = "bold yellow"
format = "[ 🕙 $time ]($style) "

[os]
disabled = false
format = "[$symbol](#blue) "

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[directory]
style = "fg:#e3e5e5 bg:transparent"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = "[$symbol $branch](bold purple) "

[git_status]
format     = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead      = "[⇡$count ](bold cyan)"
behind     = "[⇣$count ](bold cyan)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bold cyan)"
staged     = "[+$count ](bold green)"
modified   = "[●$count ](bold yellow)"
untracked  = "[?$count ](bold white)"
deleted    = "[✘$count ](bold red)"
conflicted = "[⚡$count ](bold red)"

[nodejs]
symbol = ""
format = "[$symbol $version](green) "

[rust]
symbol = ""
format = "[$symbol $version](red) "

[golang]
symbol = ""
format = "[$symbol $version](cyan) "

[php]
symbol = ""
format = "[$symbol $version](purple) "

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vimcmd_symbol  = "[❮](blue)"
